## Packages

In [1]:
# at top of notebook to auto-relaod
%load_ext autoreload
%autoreload 2

In [21]:
import pandas as pd
import numpy as np
from scipy import stats
import os
import pyreadstat.pyreadstat as ps
from IPython.display import clear_output

## Block functions

## Generalized Univariate function

In [41]:
# Read SAS file in chunks
sasfile1 = "../raw_data/test_data/app_0618_rs_exc_g2ch.sas7bdat"
chunk_size=5000
data_chunked = pd.read_sas(sasfile1, chunksize=chunk_size, iterator=True, format = 'sas7bdat', encoding="latin-1")

# Holds data chunks 
df_list = [] 

# Extracting and appending chunks
for chunk_count, chunk in enumerate(data_chunked):
    if chunk_count == 0:
        clear_output(wait=True)
    df_list.append(chunk)
    print(f"Update: Extracted chunk #{chunk_count+1} ({len(chunk)} rows)")
df = pd.concat(df_list)
print(f"Finished concatenating all {chunk_count + 1} chunks!")

Update: Extracted chunk #1 (5000 rows)
Update: Extracted chunk #2 (5000 rows)
Update: Extracted chunk #3 (3274 rows)
Finished concatenating all 3 chunks!

In [8]:
df

,KEY_ED,KEY_ED_ed,KEY_ED_ip,AGE,AMONTH,AWEEKEND,DIED_VISIT,DISCWT,DISP_ED,DQTR,...,S_DISC_U,S_HOSP_U,TOTAL_EDVISITS,chemo,radio,num_comorbidities,age_cat,dehydr_v2,obstr_v2,TOTCHG_ED_IP
0,1.200600e+12,NaN,1.200600e+12,60.0,3.0,1.0,0.0,4.285226,9.0,1.0,...,1092280.0,31.0,51942.0,0.0,0.0,5.0,Below 75,1.0,0.0,22084.0
1,1.200600e+12,NaN,1.200600e+12,76.0,8.0,0.0,0.0,4.676267,9.0,3.0,...,357075.0,16.0,73366.0,0.0,0.0,7.0,75 or more,1.0,0.0,36679.0
2,1.200600e+12,NaN,1.200600e+12,68.0,5.0,0.0,0.0,4.285226,9.0,2.0,...,1092280.0,31.0,51942.0,0.0,0.0,6.0,Below 75,0.0,1.0,95641.0
3,1.200600e+12,NaN,1.200600e+12,85.0,12.0,0.0,0.0,4.285226,9.0,1.0,...,1092280.0,31.0,19240.0,0.0,0.0,5.0,75 or more,1.0,1.0,253762.0
4,1.200600e+12,NaN,1.200600e+12,49.0,12.0,0.0,0.0,4.395115,9.0,4.0,...,534290.0,19.0,9809.0,0.0,0.0,2.0,Below 75,1.0,0.0,8385.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13269,4.201807e+12,NaN,4.201807e+12,58.0,8.0,0.0,0.0,0.763896,9.0,3.0,...,195397.0,2.0,103289.0,0.0,0.0,2.0,Below 75,1.0,0.0,40639.0
13270,4.201807e+12,NaN,4.201807e+12,53.0,7.0,0.0,0.0,3.641506,9.0,3.0,...,536687.0,14.0,48387.0,1.0,1.0,4.0,Below 75,1.0,0.0,62342.0
13271,4.201807e+12,NaN,4.201807e+12,50.0,5.0,1.0,0.0,2.489787,9.0,2.0,...,122098.0,2.0,75508.0,0.0,0.0,4.0,Below 75,1.0,0.0,26296.0
13272,4.201807e+12,NaN,4.201807e+12,83.0,10.0,0.0,0.0,4.392062,9.0,4.0,...,1047430.0,17.0,59946.0,0.0,0.0,8.0,75 or more,1.0,0.0,40933.0
13273,4.201807e+12,NaN,4.201807e+12,76.0,10.0,0.0,0.0,6.021718,9.0,4.0,...,63727.0,3.0,19930.0,0.0,0.0,3.0,75 or more,1.0,0.0,24809.0